# Creating a Logistic Regression to predict Absenteeism

## Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Load the Data 

In [2]:
data_preprocessed = pd.read_csv("Absenteeism_preprocessed.csv")
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create the Targets

Logistic Regression is a type of classification

Classes:
1. Excessively Absent >= 4
1. Moderately Absent <= 3

We will take the median value of the "Absenteeism Time in Hours" and use it as a cut-off line.

We have balanced the dataset with the median.

This will prevent our model from learning to output onle 0s or 1s

In [3]:
median = data_preprocessed["Absenteeism Time in Hours"].median()
median

3.0

__np.where(condition, value if True, value if False):__ checks if a condition has been satisfied and assigns a value accordingly. 

In [4]:
targets = np.where(data_preprocessed["Absenteeism Time in Hours"] > median, 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed["Excessive Absenteeism"] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [6]:
targets.sum()

319

In [7]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [8]:
data_with_targets = data_preprocessed.drop(["Absenteeism Time in Hours",
                                           "Day of the Week", 
                                           "Daily Work Load Average", 
                                           "Distance to Work"], axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Transportation Expense  Age  \
0         0         0         0         1      7                     289   33   
1         0         0         0         0      7                     118   50   
2         0         0         0         1      7                     179   38   
3         1         0         0         0      7                     279   39   
4         0         0         0         1      7                     289   33   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [9]:
data_with_targets is data_preprocessed 

# True: the two variables refer to the same object
# False: the two variables refer to different objects.

False

## Select the Inputs for the Regression

__DataFrame.iloc[row indices, column indices]:__ selects (slices) data by position when given rows and columns wanted.

In [10]:
data_with_targets.shape

(700, 12)

In [11]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

## Standardize the Data

In [12]:
# from sklearn.preprocessing import StandardScaler

In [13]:
# absenteeism_scaler = StandardScaler()

In [14]:
# Our custom scaler will not standardize all inputs, but only the ones we choose.

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [15]:
columns_to_scale = ['Month', 'Transportation Expense', 'Age', 'Body Mass Index', 'Children', 'Pets']

In [16]:
absenteeism_scaler = CustomScaler(columns_to_scale)

C:\Users\Ricar\anaconda3\envs\365\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [17]:
absenteeism_scaler.fit(unscaled_inputs) # Calculate and store the mean and the standard deviation

scaled_inputs = absenteeism_scaler.transform(unscaled_inputs) # Does the actual scaling. 

In [18]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
0           0         0         0         1  0.182726                1.005844   
1           0         0         0         0  0.182726               -1.574681   
2           0         0         0         1  0.182726               -0.654143   
3           1         0         0         0  0.182726                0.854936   
4           0         0         0         1  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695         1         0         0         0 -0.388293               -0.654143   
696         1         0         0         0 -0.388293                0.040034   
697         1         0         0         0 -0.388293                1.624567   
698         0         0         0         1 -0.388293                0.190942   
699         0         0         0         1 -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [19]:
scaled_inputs.shape

(700, 11)

## Split the data into Train and Test and shuffle

Import the relevant module

In [20]:
from sklearn.model_selection import train_test_split

## Split

__skleand.mode_selection.train_test_split(inputs, targets):__ splits arrays or matrices into random train and test subsets.

In [21]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=.8, shuffle=True, random_state=23)

In [22]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(560, 11)
(140, 11)
(560,)
(140,)


## Logistic Regression

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

__sklearn.linear_model.LogisticRegression.fit(x, y):__ fits the model according to the giving training data.

In [24]:
reg = LogisticRegression()
reg.fit(x_train, y_train)

LogisticRegression()

__sklearn.linear_model.LogisticRegression.score(inputs, targets):__ returns the mean accuracy on the given test data and labels. 

In [25]:
reg.score(x_train, y_train)

0.7696428571428572

### Manually check the accuracy

Accuracy means that x% of the model outputs match the targets.

__sklearn.linear_model.LogisticRegression.predict(inputs):__ predicts class labels (logistic regression outputs) for given input samples.

In [26]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,

In [27]:
y_train

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,

In [28]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.7696428571428572

## Finding the Intercept and Coefficients

In [29]:
intercept = reg.intercept_
intercept

array([-1.63521019])

In [30]:
coefficients = reg.coef_
coefficients

array([[ 2.73321485,  0.45113124,  3.24286689,  0.87321271,  0.0684299 ,
         0.52841979, -0.25911011,  0.28878282,  0.01763324,  0.46822137,
        -0.28911408]])

In [31]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
0           0         0         0         1  0.182726                1.005844   
1           0         0         0         0  0.182726               -1.574681   
2           0         0         0         1  0.182726               -0.654143   
3           1         0         0         0  0.182726                0.854936   
4           0         0         0         1  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695         1         0         0         0 -0.388293               -0.654143   
696         1         0         0         0 -0.388293                0.040034   
697         1         0         0         0 -0.388293                1.624567   
698         0         0         0         1 -0.388293                0.190942   
699         0         0         0         1 -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [32]:
feature_name = unscaled_inputs.columns.values
feature_name

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [33]:
summary_table = pd.DataFrame(columns=["Feature Name"], data=feature_name)
summary_table["Coefficients"] = np.transpose(coefficients) # transpose beacuase ndarrays are rows and not columns. 
summary_table

Feature Name  Coefficients
0                 Reason_1      2.733215
1                 Reason_2      0.451131
2                 Reason_3      3.242867
3                 Reason_4      0.873213
4                    Month      0.068430
5   Transportation Expense      0.528420
6                      Age     -0.259110
7          Body Mass Index      0.288783
8                Education      0.017633
9                 Children      0.468221
10                    Pets     -0.289114

In [34]:
summary_table.index = summary_table.index + 1 # In this way we will "shift" up all indices by 1.
summary_table

Feature Name  Coefficients
1                 Reason_1      2.733215
2                 Reason_2      0.451131
3                 Reason_3      3.242867
4                 Reason_4      0.873213
5                    Month      0.068430
6   Transportation Expense      0.528420
7                      Age     -0.259110
8          Body Mass Index      0.288783
9                Education      0.017633
10                Children      0.468221
11                    Pets     -0.289114

In [35]:
summary_table.loc[0] = ["Intercept", intercept[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficients
0                Intercept     -1.635210
1                 Reason_1      2.733215
2                 Reason_2      0.451131
3                 Reason_3      3.242867
4                 Reason_4      0.873213
5                    Month      0.068430
6   Transportation Expense      0.528420
7                      Age     -0.259110
8          Body Mass Index      0.288783
9                Education      0.017633
10                Children      0.468221
11                    Pets     -0.289114

## Interpreting the Coefficients

The coler the coefficients/weights to 0, the smaller the weight.

Standardized coefficients are basically: the coefficients of a regression where all variables have been standardized.

Whichever weights is bigger, its corresponding feature is more important. 

In [36]:
summary_table["Odds Ratio"] = np.exp(summary_table.Coefficients)
summary_table

Feature Name  Coefficients  Odds Ratio
0                Intercept     -1.635210    0.194911
1                 Reason_1      2.733215   15.382259
2                 Reason_2      0.451131    1.570087
3                 Reason_3      3.242867   25.607029
4                 Reason_4      0.873213    2.394592
5                    Month      0.068430    1.070826
6   Transportation Expense      0.528420    1.696250
7                      Age     -0.259110    0.771738
8          Body Mass Index      0.288783    1.334802
9                Education      0.017633    1.017790
10                Children      0.468221    1.597151
11                    Pets     -0.289114    0.748927

__DataFrame.sort_values( Series ):__ sorts the values in a data frame with respect to a given column (*Series*)

In [37]:
summary_table.sort_values("Odds Ratio", ascending=False)

Feature Name  Coefficients  Odds Ratio
3                 Reason_3      3.242867   25.607029
1                 Reason_1      2.733215   15.382259
4                 Reason_4      0.873213    2.394592
6   Transportation Expense      0.528420    1.696250
10                Children      0.468221    1.597151
2                 Reason_2      0.451131    1.570087
8          Body Mass Index      0.288783    1.334802
5                    Month      0.068430    1.070826
9                Education      0.017633    1.017790
7                      Age     -0.259110    0.771738
11                    Pets     -0.289114    0.748927
0                Intercept     -1.635210    0.194911

A features is not particularly important:
- If its coefficient is around 0
- If its odds ratio is around 1

A weight(coefficient) of 0 implies that no matter the feature value, we will multiply it by 0 (in the model)

For a unit change in the standardized feature, the odds increase by a multiple equal to the odds ratio (1 = no change)

When we standardized the inputs, we also standardize the dummies.

Bad Practice

When we standardize we lose the whole interpretability of a dummy. 

__Backward Elimination__: 
- The idea is that we can simplify our model by removing all features which have close to no contribution to the model. 
- When we have the p-values, we get rid of all coefficients with p-values < __0.05__
- _If the weight is small enough, it won't make a difference anyway.._
- If we remove these variables, the rest of our model should not really change in terms of coefficient values. 

## Testing the Model

In [38]:
reg.score(x_test, y_test)

0.7642857142857142

So based on data that the model has __NEVER__ seen before, in 76% of the cases, the model will predict (correctly) if the person is going to be excessively absent.

__sklearn.linear_model.LogisticRegression.predict_proba(x):__ returns the probability estimates for all possible outputs (classes)

In [39]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.1781555 , 0.8218445 ],
       [0.85071866, 0.14928134],
       [0.22220583, 0.77779417],
       [0.1226066 , 0.8773934 ],
       [0.84312111, 0.15687889],
       [0.52380497, 0.47619503],
       [0.37718926, 0.62281074],
       [0.84822044, 0.15177956],
       [0.33178733, 0.66821267],
       [0.56548804, 0.43451196],
       [0.48278241, 0.51721759],
       [0.76993129, 0.23006871],
       [0.82991264, 0.17008736],
       [0.37831571, 0.62168429],
       [0.18457843, 0.81542157],
       [0.77677979, 0.22322021],
       [0.77337383, 0.22662617],
       [0.25044593, 0.74955407],
       [0.091281  , 0.908719  ],
       [0.47241413, 0.52758587],
       [0.75217315, 0.24782685],
       [0.32282366, 0.67717634],
       [0.86950034, 0.13049966],
       [0.90133812, 0.09866188],
       [0.29421981, 0.70578019],
       [0.42150756, 0.57849244],
       [0.86950034, 0.13049966],
       [0.73195474, 0.26804526],
       [0.76993129, 0.23006871],
       [0.73195474, 0.26804526],
       [0.

In [40]:
predicted_proba.shape

(140, 2)

In [41]:
predicted_proba[:, 1]

array([0.8218445 , 0.14928134, 0.77779417, 0.8773934 , 0.15687889,
       0.47619503, 0.62281074, 0.15177956, 0.66821267, 0.43451196,
       0.51721759, 0.23006871, 0.17008736, 0.62168429, 0.81542157,
       0.22322021, 0.22662617, 0.74955407, 0.908719  , 0.52758587,
       0.24782685, 0.67717634, 0.13049966, 0.09866188, 0.70578019,
       0.57849244, 0.13049966, 0.26804526, 0.23006871, 0.26804526,
       0.67912769, 0.65949341, 0.25018918, 0.13273261, 0.46654367,
       0.23094402, 0.13049966, 0.49852836, 0.8653199 , 0.68337017,
       0.89990889, 0.66749339, 0.76682405, 0.83836582, 0.76866809,
       0.81268808, 0.8537986 , 0.46159973, 0.6530655 , 0.69815185,
       0.28763958, 0.37902201, 0.40905899, 0.25148671, 0.81834402,
       0.80284417, 0.5937474 , 0.50551636, 0.36532781, 0.8537986 ,
       0.24420288, 0.15967626, 0.78383409, 0.29979725, 0.65509247,
       0.22662617, 0.3352665 , 0.53512978, 0.23006871, 0.43931852,
       0.17015826, 0.52209436, 0.16197302, 0.26422949, 0.94615

Saving the model is equivalent to save the "reg" object.

## Save the Model

__pickle [module]:__ is a Python module used to convert a Python object into a character stream

In [42]:
import pickle

In [44]:
with open("model", "wb") as file:
    pickle.dump(reg, file)

The information in the absenteeism_scaler is used to preprocess new data.

In [45]:
with open("scaler", "wb") as file:
    pickle.dump(absenteeism_scaler, file)

The second step of the deployment is about creating a mechanism to load the saved model and make predictions.